// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/katlc/agentapi/agent.proto

package agentapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusRequest) Reset() {
	*x = GetNodeStatusRequest{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusRequest) ProtoMessage() {}

func (x *GetNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{0}
}

type NodeStatus struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion              string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	MachineId               string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	AgentStartId            string                 `protobuf:"bytes,3,opt,name=agent_start_id,json=agentStartId,proto3" json:"agent_start_id,omitempty"`
	AgentStartedAt          string                 `protobuf:"bytes,4,opt,name=agent_started_at,json=agentStartedAt,proto3" json:"agent_started_at,omitempty"`
	SupportedApiVersions    []string               `protobuf:"bytes,5,rep,name=supported_api_versions,json=supportedApiVersions,proto3" json:"supported_api_versions,omitempty"`
	SupportedOperationKinds []string               `protobuf:"bytes,6,rep,name=supported_operation_kinds,json=supportedOperationKinds,proto3" json:"supported_operation_kinds,omitempty"`
	OperationLockHeld       bool                   `protobuf:"varint,7,opt,name=operation_lock_held,json=operationLockHeld,proto3" json:"operation_lock_held,omitempty"`
	ActiveOperationIds      []string               `protobuf:"bytes,8,rep,name=active_operation_ids,json=activeOperationIds,proto3" json:"active_operation_ids,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatus) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *NodeStatus) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *NodeStatus) GetAgentStartId() string {
	if x != nil {
		return x.AgentStartId
	}
	return ""
}

func (x *NodeStatus) GetAgentStartedAt() string {
	if x != nil {
		return x.AgentStartedAt
	}
	return ""
}

func (x *NodeStatus) GetSupportedApiVersions() []string {
	if x != nil {
		return x.SupportedApiVersions
	}
	return nil
}

func (x *NodeStatus) GetSupportedOperationKinds() []string {
	if x != nil {
		return x.SupportedOperationKinds
	}
	return nil
}

func (x *NodeStatus) GetOperationLockHeld() bool {
	if x != nil {
		return x.OperationLockHeld
	}
	return false
}

func (x *NodeStatus) GetActiveOperationIds() []string {
	if x != nil {
		return x.ActiveOperationIds
	}
	return nil
}

type SubmitOperationRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion                  string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind                        string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ClientRequestId             string                 `protobuf:"bytes,3,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	OperationKind               string                 `protobuf:"bytes,4,opt,name=operation_kind,json=operationKind,proto3" json:"operation_kind,omitempty"`
	Actor                       string                 `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	ExpectedMachineId           string                 `protobuf:"bytes,6,opt,name=expected_machine_id,json=expectedMachineId,proto3" json:"expected_machine_id,omitempty"`
	ExpectedCurrentGenerationId string                 `protobuf:"bytes,7,opt,name=expected_current_generation_id,json=expectedCurrentGenerationId,proto3" json:"expected_current_generation_id,omitempty"`
	ExpectedClusterIntentDigest string                 `protobuf:"bytes,8,opt,name=expected_cluster_intent_digest,json=expectedClusterIntentDigest,proto3" json:"expected_cluster_intent_digest,omitempty"`
	RequestDigest               string                 `protobuf:"bytes,9,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	DryRun                      bool                   `protobuf:"varint,10,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	OperationTimeout            string                 `protobuf:"bytes,11,opt,name=operation_timeout,json=operationTimeout,proto3" json:"operation_timeout,omitempty"`
	Request                     *structpb.Struct       `protobuf:"bytes,12,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SubmitOperationRequest) Reset() {
	*x = SubmitOperationRequest{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOperationRequest) ProtoMessage() {}

func (x *SubmitOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOperationRequest.ProtoReflect.Descriptor instead.
func (*SubmitOperationRequest) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitOperationRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SubmitOperationRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SubmitOperationRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *SubmitOperationRequest) GetOperationKind() string {
	if x != nil {
		return x.OperationKind
	}
	return ""
}

func (x *SubmitOperationRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *SubmitOperationRequest) GetExpectedMachineId() string {
	if x != nil {
		return x.ExpectedMachineId
	}
	return ""
}

func (x *SubmitOperationRequest) GetExpectedCurrentGenerationId() string {
	if x != nil {
		return x.ExpectedCurrentGenerationId
	}
	return ""
}

func (x *SubmitOperationRequest) GetExpectedClusterIntentDigest() string {
	if x != nil {
		return x.ExpectedClusterIntentDigest
	}
	return ""
}

func (x *SubmitOperationRequest) GetRequestDigest() string {
	if x != nil {
		return x.RequestDigest
	}
	return ""
}

func (x *SubmitOperationRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *SubmitOperationRequest) GetOperationTimeout() string {
	if x != nil {
		return x.OperationTimeout
	}
	return ""
}

func (x *SubmitOperationRequest) GetRequest() *structpb.Struct {
	if x != nil {
		return x.Request
	}
	return nil
}

type OperationAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	OperationKind string                 `protobuf:"bytes,2,opt,name=operation_kind,json=operationKind,proto3" json:"operation_kind,omitempty"`
	RequestDigest string                 `protobuf:"bytes,3,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	RecordPath    string                 `protobuf:"bytes,4,opt,name=record_path,json=recordPath,proto3" json:"record_path,omitempty"`
	AcceptedAt    string                 `protobuf:"bytes,5,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	InitialStatus *OperationStatus       `protobuf:"bytes,6,opt,name=initial_status,json=initialStatus,proto3" json:"initial_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationAccepted) Reset() {
	*x = OperationAccepted{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationAccepted) ProtoMessage() {}

func (x *OperationAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationAccepted.ProtoReflect.Descriptor instead.
func (*OperationAccepted) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{3}
}

func (x *OperationAccepted) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationAccepted) GetOperationKind() string {
	if x != nil {
		return x.OperationKind
	}
	return ""
}

func (x *OperationAccepted) GetRequestDigest() string {
	if x != nil {
		return x.RequestDigest
	}
	return ""
}

func (x *OperationAccepted) GetRecordPath() string {
	if x != nil {
		return x.RecordPath
	}
	return ""
}

func (x *OperationAccepted) GetAcceptedAt() string {
	if x != nil {
		return x.AcceptedAt
	}
	return ""
}

func (x *OperationAccepted) GetInitialStatus() *OperationStatus {
	if x != nil {
		return x.InitialStatus
	}
	return nil
}

type GetOperationRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OperationId           string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExpectedRequestDigest string                 `protobuf:"bytes,2,opt,name=expected_request_digest,json=expectedRequestDigest,proto3" json:"expected_request_digest,omitempty"`
	IncludeDiagnostics    string                 `protobuf:"bytes,3,opt,name=include_diagnostics,json=includeDiagnostics,proto3" json:"include_diagnostics,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetOperationRequest) GetExpectedRequestDigest() string {
	if x != nil {
		return x.ExpectedRequestDigest
	}
	return ""
}

func (x *GetOperationRequest) GetIncludeDiagnostics() string {
	if x != nil {
		return x.IncludeDiagnostics
	}
	return ""
}

type OperationStatus struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	OperationId             string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	OperationKind           string                 `protobuf:"bytes,2,opt,name=operation_kind,json=operationKind,proto3" json:"operation_kind,omitempty"`
	RequestDigest           string                 `protobuf:"bytes,3,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	Phase                   string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	PhaseIndex              int32                  `protobuf:"varint,5,opt,name=phase_index,json=phaseIndex,proto3" json:"phase_index,omitempty"`
	CompletedPhases         []string               `protobuf:"bytes,6,rep,name=completed_phases,json=completedPhases,proto3" json:"completed_phases,omitempty"`
	Terminal                bool                   `protobuf:"varint,7,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Result                  string                 `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	CandidateGenerationId   string                 `protobuf:"bytes,9,opt,name=candidate_generation_id,json=candidateGenerationId,proto3" json:"candidate_generation_id,omitempty"`
	ExternalMutationStarted bool                   `protobuf:"varint,10,opt,name=external_mutation_started,json=externalMutationStarted,proto3" json:"external_mutation_started,omitempty"`
	MutationScopes          []string               `protobuf:"bytes,11,rep,name=mutation_scopes,json=mutationScopes,proto3" json:"mutation_scopes,omitempty"`
	ResourceLocks           []string               `protobuf:"bytes,12,rep,name=resource_locks,json=resourceLocks,proto3" json:"resource_locks,omitempty"`
	LatestJournalSeq        int32                  `protobuf:"varint,13,opt,name=latest_journal_seq,json=latestJournalSeq,proto3" json:"latest_journal_seq,omitempty"`
	UpdatedAt               string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	NextAction              string                 `protobuf:"bytes,15,opt,name=next_action,json=nextAction,proto3" json:"next_action,omitempty"`
	Diagnostics             []*DiagnosticArtifact  `protobuf:"bytes,16,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	RecoveryRequired        bool                   `protobuf:"varint,17,opt,name=recovery_required,json=recoveryRequired,proto3" json:"recovery_required,omitempty"`
	FailureReason           string                 `protobuf:"bytes,18,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{5}
}

func (x *OperationStatus) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationStatus) GetOperationKind() string {
	if x != nil {
		return x.OperationKind
	}
	return ""
}

func (x *OperationStatus) GetRequestDigest() string {
	if x != nil {
		return x.RequestDigest
	}
	return ""
}

func (x *OperationStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *OperationStatus) GetPhaseIndex() int32 {
	if x != nil {
		return x.PhaseIndex
	}
	return 0
}

func (x *OperationStatus) GetCompletedPhases() []string {
	if x != nil {
		return x.CompletedPhases
	}
	return nil
}

func (x *OperationStatus) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *OperationStatus) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *OperationStatus) GetCandidateGenerationId() string {
	if x != nil {
		return x.CandidateGenerationId
	}
	return ""
}

func (x *OperationStatus) GetExternalMutationStarted() bool {
	if x != nil {
		return x.ExternalMutationStarted
	}
	return false
}

func (x *OperationStatus) GetMutationScopes() []string {
	if x != nil {
		return x.MutationScopes
	}
	return nil
}

func (x *OperationStatus) GetResourceLocks() []string {
	if x != nil {
		return x.ResourceLocks
	}
	return nil
}

func (x *OperationStatus) GetLatestJournalSeq() int32 {
	if x != nil {
		return x.LatestJournalSeq
	}
	return 0
}

func (x *OperationStatus) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OperationStatus) GetNextAction() string {
	if x != nil {
		return x.NextAction
	}
	return ""
}

func (x *OperationStatus) GetDiagnostics() []*DiagnosticArtifact {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *OperationStatus) GetRecoveryRequired() bool {
	if x != nil {
		return x.RecoveryRequired
	}
	return false
}

func (x *OperationStatus) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type DiagnosticArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Redacted      bool                   `protobuf:"varint,4,opt,name=redacted,proto3" json:"redacted,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticArtifact) Reset() {
	*x = DiagnosticArtifact{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticArtifact) ProtoMessage() {}

func (x *DiagnosticArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticArtifact.ProtoReflect.Descriptor instead.
func (*DiagnosticArtifact) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DiagnosticArtifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *DiagnosticArtifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiagnosticArtifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *DiagnosticArtifact) GetRedacted() bool {
	if x != nil {
		return x.Redacted
	}
	return false
}

func (x *DiagnosticArtifact) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type WatchOperationRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OperationId           string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExpectedRequestDigest string                 `protobuf:"bytes,2,opt,name=expected_request_digest,json=expectedRequestDigest,proto3" json:"expected_request_digest,omitempty"`
	AfterJournalSeq       int32                  `protobuf:"varint,3,opt,name=after_journal_seq,json=afterJournalSeq,proto3" json:"after_journal_seq,omitempty"`
	WatchTimeout          string                 `protobuf:"bytes,4,opt,name=watch_timeout,json=watchTimeout,proto3" json:"watch_timeout,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WatchOperationRequest) Reset() {
	*x = WatchOperationRequest{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchOperationRequest) ProtoMessage() {}

func (x *WatchOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchOperationRequest.ProtoReflect.Descriptor instead.
func (*WatchOperationRequest) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WatchOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *WatchOperationRequest) GetExpectedRequestDigest() string {
	if x != nil {
		return x.ExpectedRequestDigest
	}
	return ""
}

func (x *WatchOperationRequest) GetAfterJournalSeq() int32 {
	if x != nil {
		return x.AfterJournalSeq
	}
	return 0
}

func (x *WatchOperationRequest) GetWatchTimeout() string {
	if x != nil {
		return x.WatchTimeout
	}
	return ""
}

type OperationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	JournalSeq    int32                  `protobuf:"varint,2,opt,name=journal_seq,json=journalSeq,proto3" json:"journal_seq,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Terminal      bool                   `protobuf:"varint,5,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Status        *OperationStatus       `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationEvent) Reset() {
	*x = OperationEvent{}
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationEvent) ProtoMessage() {}

func (x *OperationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_katlc_agentapi_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationEvent.ProtoReflect.Descriptor instead.
func (*OperationEvent) Descriptor() ([]byte, []int) {
	return file_internal_katlc_agentapi_agent_proto_rawDescGZIP(), []int{8}
}

func (x *OperationEvent) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationEvent) GetJournalSeq() int32 {
	if x != nil {
		return x.JournalSeq
	}
	return 0
}

func (x *OperationEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OperationEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *OperationEvent) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *OperationEvent) GetStatus() *OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_internal_katlc_agentapi_agent_proto protoreflect.FileDescriptor

const file_internal_katlc_agentapi_agent_proto_rawDesc = "" +
	"\n" +
	"#internal/katlc/agentapi/agent.proto\x12\rkatl.agent.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x16\n" +
	"\x14GetNodeStatusRequest\"\xf0\x02\n" +
	"\n" +
	"NodeStatus\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x12$\n" +
	"\x0eagent_start_id\x18\x03 \x01(\tR\fagentStartId\x12(\n" +
	"\x10agent_started_at\x18\x04 \x01(\tR\x0eagentStartedAt\x124\n" +
	"\x16supported_api_versions\x18\x05 \x03(\tR\x14supportedApiVersions\x12:\n" +
	"\x19supported_operation_kinds\x18\x06 \x03(\tR\x17supportedOperationKinds\x12.\n" +
	"\x13operation_lock_held\x18\a \x01(\bR\x11operationLockHeld\x120\n" +
	"\x14active_operation_ids\x18\b \x03(\tR\x12activeOperationIds\"\x90\x04\n" +
	"\x16SubmitOperationRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12*\n" +
	"\x11client_request_id\x18\x03 \x01(\tR\x0fclientRequestId\x12%\n" +
	"\x0eoperation_kind\x18\x04 \x01(\tR\roperationKind\x12\x14\n" +
	"\x05actor\x18\x05 \x01(\tR\x05actor\x12.\n" +
	"\x13expected_machine_id\x18\x06 \x01(\tR\x11expectedMachineId\x12C\n" +
	"\x1eexpected_current_generation_id\x18\a \x01(\tR\x1bexpectedCurrentGenerationId\x12C\n" +
	"\x1eexpected_cluster_intent_digest\x18\b \x01(\tR\x1bexpectedClusterIntentDigest\x12%\n" +
	"\x0erequest_digest\x18\t \x01(\tR\rrequestDigest\x12\x17\n" +
	"\adry_run\x18\n" +
	" \x01(\bR\x06dryRun\x12+\n" +
	"\x11operation_timeout\x18\v \x01(\tR\x10operationTimeout\x121\n" +
	"\arequest\x18\f \x01(\v2\x17.google.protobuf.StructR\arequest\"\x8d\x02\n" +
	"\x11OperationAccepted\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0eoperation_kind\x18\x02 \x01(\tR\roperationKind\x12%\n" +
	"\x0erequest_digest\x18\x03 \x01(\tR\rrequestDigest\x12\x1f\n" +
	"\vrecord_path\x18\x04 \x01(\tR\n" +
	"recordPath\x12\x1f\n" +
	"\vaccepted_at\x18\x05 \x01(\tR\n" +
	"acceptedAt\x12E\n" +
	"\x0einitial_status\x18\x06 \x01(\v2\x1e.katl.agent.v1.OperationStatusR\rinitialStatus\"\xa1\x01\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x126\n" +
	"\x17expected_request_digest\x18\x02 \x01(\tR\x15expectedRequestDigest\x12/\n" +
	"\x13include_diagnostics\x18\x03 \x01(\tR\x12includeDiagnostics\"\xe3\x05\n" +
	"\x0fOperationStatus\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0eoperation_kind\x18\x02 \x01(\tR\roperationKind\x12%\n" +
	"\x0erequest_digest\x18\x03 \x01(\tR\rrequestDigest\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x1f\n" +
	"\vphase_index\x18\x05 \x01(\x05R\n" +
	"phaseIndex\x12)\n" +
	"\x10completed_phases\x18\x06 \x03(\tR\x0fcompletedPhases\x12\x1a\n" +
	"\bterminal\x18\a \x01(\bR\bterminal\x12\x16\n" +
	"\x06result\x18\b \x01(\tR\x06result\x126\n" +
	"\x17candidate_generation_id\x18\t \x01(\tR\x15candidateGenerationId\x12:\n" +
	"\x19external_mutation_started\x18\n" +
	" \x01(\bR\x17externalMutationStarted\x12'\n" +
	"\x0fmutation_scopes\x18\v \x03(\tR\x0emutationScopes\x12%\n" +
	"\x0eresource_locks\x18\f \x03(\tR\rresourceLocks\x12,\n" +
	"\x12latest_journal_seq\x18\r \x01(\x05R\x10latestJournalSeq\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vnext_action\x18\x0f \x01(\tR\n" +
	"nextAction\x12C\n" +
	"\vdiagnostics\x18\x10 \x03(\v2!.katl.agent.v1.DiagnosticArtifactR\vdiagnostics\x12+\n" +
	"\x11recovery_required\x18\x11 \x01(\bR\x10recoveryRequired\x12%\n" +
	"\x0efailure_reason\x18\x12 \x01(\tR\rfailureReason\"\x9c\x01\n" +
	"\x12DiagnosticArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1a\n" +
	"\bredacted\x18\x04 \x01(\bR\bredacted\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xc3\x01\n" +
	"\x15WatchOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x126\n" +
	"\x17expected_request_digest\x18\x02 \x01(\tR\x15expectedRequestDigest\x12*\n" +
	"\x11after_journal_seq\x18\x03 \x01(\x05R\x0fafterJournalSeq\x12#\n" +
	"\rwatch_timeout\x18\x04 \x01(\tR\fwatchTimeout\"\xdd\x01\n" +
	"\x0eOperationEvent\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vjournal_seq\x18\x02 \x01(\x05R\n" +
	"journalSeq\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x1a\n" +
	"\bterminal\x18\x05 \x01(\bR\bterminal\x126\n" +
	"\x06status\x18\x06 \x01(\v2\x1e.katl.agent.v1.OperationStatusR\x06status2\xe6\x02\n" +
	"\n" +
	"KatlcAgent\x12O\n" +
	"\rGetNodeStatus\x12#.katl.agent.v1.GetNodeStatusRequest\x1a\x19.katl.agent.v1.NodeStatus\x12Z\n" +
	"\x0fSubmitOperation\x12%.katl.agent.v1.SubmitOperationRequest\x1a .katl.agent.v1.OperationAccepted\x12R\n" +
	"\fGetOperation\x12\".katl.agent.v1.GetOperationRequest\x1a\x1e.katl.agent.v1.OperationStatus\x12W\n" +
	"\x0eWatchOperation\x12$.katl.agent.v1.WatchOperationRequest\x1a\x1d.katl.agent.v1.OperationEvent0\x01B9Z7github.com/zariel/katl/internal/katlc/agentapi;agentapib\x06proto3"

var (
	file_internal_katlc_agentapi_agent_proto_rawDescOnce sync.Once
	file_internal_katlc_agentapi_agent_proto_rawDescData []byte
)

func file_internal_katlc_agentapi_agent_proto_rawDescGZIP() []byte {
	file_internal_katlc_agentapi_agent_proto_rawDescOnce.Do(func() {
		file_internal_katlc_agentapi_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_katlc_agentapi_agent_proto_rawDesc), len(file_internal_katlc_agentapi_agent_proto_rawDesc)))
	})
	return file_internal_katlc_agentapi_agent_proto_rawDescData
}

var file_internal_katlc_agentapi_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_katlc_agentapi_agent_proto_goTypes = []any{
	(*GetNodeStatusRequest)(nil),   // 0: katl.agent.v1.GetNodeStatusRequest
	(*NodeStatus)(nil),             // 1: katl.agent.v1.NodeStatus
	(*SubmitOperationRequest)(nil), // 2: katl.agent.v1.SubmitOperationRequest
	(*OperationAccepted)(nil),      // 3: katl.agent.v1.OperationAccepted
	(*GetOperationRequest)(nil),    // 4: katl.agent.v1.GetOperationRequest
	(*OperationStatus)(nil),        // 5: katl.agent.v1.OperationStatus
	(*DiagnosticArtifact)(nil),     // 6: katl.agent.v1.DiagnosticArtifact
	(*WatchOperationRequest)(nil),  // 7: katl.agent.v1.WatchOperationRequest
	(*OperationEvent)(nil),         // 8: katl.agent.v1.OperationEvent
	(*structpb.Struct)(nil),        // 9: google.protobuf.Struct
}
var file_internal_katlc_agentapi_agent_proto_depIdxs = []int32{
	9, // 0: katl.agent.v1.SubmitOperationRequest.request:type_name -> google.protobuf.Struct
	5, // 1: katl.agent.v1.OperationAccepted.initial_status:type_name -> katl.agent.v1.OperationStatus
	6, // 2: katl.agent.v1.OperationStatus.diagnostics:type_name -> katl.agent.v1.DiagnosticArtifact
	5, // 3: katl.agent.v1.OperationEvent.status:type_name -> katl.agent.v1.OperationStatus
	0, // 4: katl.agent.v1.KatlcAgent.GetNodeStatus:input_type -> katl.agent.v1.GetNodeStatusRequest
	2, // 5: katl.agent.v1.KatlcAgent.SubmitOperation:input_type -> katl.agent.v1.SubmitOperationRequest
	4, // 6: katl.agent.v1.KatlcAgent.GetOperation:input_type -> katl.agent.v1.GetOperationRequest
	7, // 7: katl.agent.v1.KatlcAgent.WatchOperation:input_type -> katl.agent.v1.WatchOperationRequest
	1, // 8: katl.agent.v1.KatlcAgent.GetNodeStatus:output_type -> katl.agent.v1.NodeStatus
	3, // 9: katl.agent.v1.KatlcAgent.SubmitOperation:output_type -> katl.agent.v1.OperationAccepted
	5, // 10: katl.agent.v1.KatlcAgent.GetOperation:output_type -> katl.agent.v1.OperationStatus
	8, // 11: katl.agent.v1.KatlcAgent.WatchOperation:output_type -> katl.agent.v1.OperationEvent
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_katlc_agentapi_agent_proto_init() }
func file_internal_katlc_agentapi_agent_proto_init() {
	if File_internal_katlc_agentapi_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_katlc_agentapi_agent_proto_rawDesc), len(file_internal_katlc_agentapi_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_katlc_agentapi_agent_proto_goTypes,
		DependencyIndexes: file_internal_katlc_agentapi_agent_proto_depIdxs,
		MessageInfos:      file_internal_katlc_agentapi_agent_proto_msgTypes,
	}.Build()
	File_internal_katlc_agentapi_agent_proto = out.File
	file_internal_katlc_agentapi_agent_proto_goTypes = nil
	file_internal_katlc_agentapi_agent_proto_depIdxs = nil
}
