PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
AuthorizedKeysFile /etc/ssh/authorized_keys/%u
AllowUsers katl
HostKey /var/lib/katl/ssh/host-keys/ssh_host_ed25519_key
