[Output]
Format=directory
Output=katl-runtime-root
ImageId=katl-runtime

[Content]
Bootable=no
Packages=
        kernel-core
        kernel-modules
        dracut
        systemd
        systemd-udev
        systemd-networkd
        systemd-resolved
        openssh-server
        ca-certificates
        util-linux
        iproute
        kmod
        nftables
        containerd
        crun
        coreutils
        bash
Hostname=katl-runtime
